/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevRouteImport } from './routes/dev'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as CommunitiesRouteRouteImport } from './routes/communities/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as CommunitiesIndexRouteImport } from './routes/communities/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as ProfileIdentitiesRouteImport } from './routes/profile/identities'
import { Route as ProfileAssetsRouteImport } from './routes/profile/assets'
import { Route as DevWalletsRouteImport } from './routes/dev/wallets'
import { Route as DevUiRouteImport } from './routes/dev/ui'
import { Route as DevShadcnRouteImport } from './routes/dev/shadcn'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as ProfileUsernameRouteRouteImport } from './routes/profile/$username/route'
import { Route as CommunitiesSlugRouteRouteImport } from './routes/communities/$slug/route'
import { Route as ProfileUsernameIndexRouteImport } from './routes/profile/$username/index'
import { Route as CommunitiesSlugIndexRouteImport } from './routes/communities/$slug/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminCommunitiesIndexRouteImport } from './routes/admin/communities/index'
import { Route as AdminAssetsIndexRouteImport } from './routes/admin/assets/index'
import { Route as ProfileUsernameSettingsRouteImport } from './routes/profile/$username/settings'
import { Route as ProfileUsernameIdentitiesRouteImport } from './routes/profile/$username/identities'
import { Route as ProfileUsernameAssetsRouteImport } from './routes/profile/$username/assets'
import { Route as CommunitiesSlugOverviewRouteImport } from './routes/communities/$slug/overview'
import { Route as AdminAssetsCreateRouteImport } from './routes/admin/assets/create'
import { Route as CommunitiesSlugCollectionsRouteRouteImport } from './routes/communities/$slug/collections/route'
import { Route as AdminUsersUserIdRouteRouteImport } from './routes/admin/users/$userId/route'
import { Route as AdminCommunitiesOrganizationIdRouteRouteImport } from './routes/admin/communities/$organizationId/route'
import { Route as AdminAssetsAssetGroupIdRouteRouteImport } from './routes/admin/assets/$assetGroupId/route'
import { Route as CommunitiesSlugCollectionsIndexRouteImport } from './routes/communities/$slug/collections/index'
import { Route as AdminUsersUserIdIndexRouteImport } from './routes/admin/users/$userId/index'
import { Route as AdminCommunitiesOrganizationIdIndexRouteImport } from './routes/admin/communities/$organizationId/index'
import { Route as AdminAssetsAssetGroupIdIndexRouteImport } from './routes/admin/assets/$assetGroupId/index'
import { Route as CommunitiesSlugCollectionsAddressRouteImport } from './routes/communities/$slug/collections/$address'
import { Route as AdminUsersUserIdSettingsRouteImport } from './routes/admin/users/$userId/settings'
import { Route as AdminUsersUserIdOverviewRouteImport } from './routes/admin/users/$userId/overview'
import { Route as AdminUsersUserIdIdentitiesRouteImport } from './routes/admin/users/$userId/identities'
import { Route as AdminUsersUserIdCommunitiesRouteImport } from './routes/admin/users/$userId/communities'
import { Route as AdminUsersUserIdAssetsRouteImport } from './routes/admin/users/$userId/assets'
import { Route as AdminCommunitiesOrganizationIdSettingsRouteImport } from './routes/admin/communities/$organizationId/settings'
import { Route as AdminCommunitiesOrganizationIdRolesRouteImport } from './routes/admin/communities/$organizationId/roles'
import { Route as AdminCommunitiesOrganizationIdOverviewRouteImport } from './routes/admin/communities/$organizationId/overview'
import { Route as AdminCommunitiesOrganizationIdOperationsRouteImport } from './routes/admin/communities/$organizationId/operations'
import { Route as AdminCommunitiesOrganizationIdMembersRouteImport } from './routes/admin/communities/$organizationId/members'
import { Route as AdminCommunitiesOrganizationIdDiscordRouteImport } from './routes/admin/communities/$organizationId/discord'
import { Route as AdminAssetsAssetGroupIdSettingsRouteImport } from './routes/admin/assets/$assetGroupId/settings'
import { Route as AdminAssetsAssetGroupIdAssetsRouteImport } from './routes/admin/assets/$assetGroupId/assets'

const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRouteRoute = CommunitiesRouteRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRoute,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunitiesRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileIdentitiesRoute = ProfileIdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileAssetsRoute = ProfileAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const DevWalletsRoute = DevWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => DevRoute,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => DevRoute,
} as any)
const DevShadcnRoute = DevShadcnRouteImport.update({
  id: '/shadcn',
  path: '/shadcn',
  getParentRoute: () => DevRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileUsernameRouteRoute = ProfileUsernameRouteRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const CommunitiesSlugRouteRoute = CommunitiesSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CommunitiesRouteRoute,
} as any)
const ProfileUsernameIndexRoute = ProfileUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const CommunitiesSlugIndexRoute = CommunitiesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunitiesSlugRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunitiesIndexRoute = AdminCommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsIndexRoute = AdminAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileUsernameSettingsRoute = ProfileUsernameSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ProfileUsernameIdentitiesRoute =
  ProfileUsernameIdentitiesRouteImport.update({
    id: '/identities',
    path: '/identities',
    getParentRoute: () => ProfileUsernameRouteRoute,
  } as any)
const ProfileUsernameAssetsRoute = ProfileUsernameAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const CommunitiesSlugOverviewRoute = CommunitiesSlugOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => CommunitiesSlugRouteRoute,
} as any)
const AdminAssetsCreateRoute = AdminAssetsCreateRouteImport.update({
  id: '/assets/create',
  path: '/assets/create',
  getParentRoute: () => AdminRoute,
} as any)
const CommunitiesSlugCollectionsRouteRoute =
  CommunitiesSlugCollectionsRouteRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => CommunitiesSlugRouteRoute,
  } as any)
const AdminUsersUserIdRouteRoute = AdminUsersUserIdRouteRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunitiesOrganizationIdRouteRoute =
  AdminCommunitiesOrganizationIdRouteRouteImport.update({
    id: '/communities/$organizationId',
    path: '/communities/$organizationId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAssetsAssetGroupIdRouteRoute =
  AdminAssetsAssetGroupIdRouteRouteImport.update({
    id: '/assets/$assetGroupId',
    path: '/assets/$assetGroupId',
    getParentRoute: () => AdminRoute,
  } as any)
const CommunitiesSlugCollectionsIndexRoute =
  CommunitiesSlugCollectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CommunitiesSlugCollectionsRouteRoute,
  } as any)
const AdminUsersUserIdIndexRoute = AdminUsersUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersUserIdRouteRoute,
} as any)
const AdminCommunitiesOrganizationIdIndexRoute =
  AdminCommunitiesOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminCommunitiesOrganizationIdRouteRoute,
  } as any)
const AdminAssetsAssetGroupIdIndexRoute =
  AdminAssetsAssetGroupIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAssetsAssetGroupIdRouteRoute,
  } as any)
const CommunitiesSlugCollectionsAddressRoute =
  CommunitiesSlugCollectionsAddressRouteImport.update({
    id: '/$address',
    path: '/$address',
    getParentRoute: () => CommunitiesSlugCollectionsRouteRoute,
  } as any)
const AdminUsersUserIdSettingsRoute =
  AdminUsersUserIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminUsersUserIdRouteRoute,
  } as any)
const AdminUsersUserIdOverviewRoute =
  AdminUsersUserIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AdminUsersUserIdRouteRoute,
  } as any)
const AdminUsersUserIdIdentitiesRoute =
  AdminUsersUserIdIdentitiesRouteImport.update({
    id: '/identities',
    path: '/identities',
    getParentRoute: () => AdminUsersUserIdRouteRoute,
  } as any)
const AdminUsersUserIdCommunitiesRoute =
  AdminUsersUserIdCommunitiesRouteImport.update({
    id: '/communities',
    path: '/communities',
    getParentRoute: () => AdminUsersUserIdRouteRoute,
  } as any)
const AdminUsersUserIdAssetsRoute = AdminUsersUserIdAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AdminUsersUserIdRouteRoute,
} as any)
const AdminCommunitiesOrganizationIdSettingsRoute =
  AdminCommunitiesOrganizationIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminCommunitiesOrganizationIdRouteRoute,
  } as any)
const AdminCommunitiesOrganizationIdRolesRoute =
  AdminCommunitiesOrganizationIdRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AdminCommunitiesOrganizationIdRouteRoute,
  } as any)
const AdminCommunitiesOrganizationIdOverviewRoute =
  AdminCommunitiesOrganizationIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AdminCommunitiesOrganizationIdRouteRoute,
  } as any)
const AdminCommunitiesOrganizationIdOperationsRoute =
  AdminCommunitiesOrganizationIdOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AdminCommunitiesOrganizationIdRouteRoute,
  } as any)
const AdminCommunitiesOrganizationIdMembersRoute =
  AdminCommunitiesOrganizationIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AdminCommunitiesOrganizationIdRouteRoute,
  } as any)
const AdminCommunitiesOrganizationIdDiscordRoute =
  AdminCommunitiesOrganizationIdDiscordRouteImport.update({
    id: '/discord',
    path: '/discord',
    getParentRoute: () => AdminCommunitiesOrganizationIdRouteRoute,
  } as any)
const AdminAssetsAssetGroupIdSettingsRoute =
  AdminAssetsAssetGroupIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminAssetsAssetGroupIdRouteRoute,
  } as any)
const AdminAssetsAssetGroupIdAssetsRoute =
  AdminAssetsAssetGroupIdAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AdminAssetsAssetGroupIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/communities': typeof CommunitiesRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/dev': typeof DevRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/communities/$slug': typeof CommunitiesSlugRouteRouteWithChildren
  '/profile/$username': typeof ProfileUsernameRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/dev/shadcn': typeof DevShadcnRoute
  '/dev/ui': typeof DevUiRoute
  '/dev/wallets': typeof DevWalletsRoute
  '/profile/assets': typeof ProfileAssetsRoute
  '/profile/identities': typeof ProfileIdentitiesRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/dev/': typeof DevIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/assets/$assetGroupId': typeof AdminAssetsAssetGroupIdRouteRouteWithChildren
  '/admin/communities/$organizationId': typeof AdminCommunitiesOrganizationIdRouteRouteWithChildren
  '/admin/users/$userId': typeof AdminUsersUserIdRouteRouteWithChildren
  '/communities/$slug/collections': typeof CommunitiesSlugCollectionsRouteRouteWithChildren
  '/admin/assets/create': typeof AdminAssetsCreateRoute
  '/communities/$slug/overview': typeof CommunitiesSlugOverviewRoute
  '/profile/$username/assets': typeof ProfileUsernameAssetsRoute
  '/profile/$username/identities': typeof ProfileUsernameIdentitiesRoute
  '/profile/$username/settings': typeof ProfileUsernameSettingsRoute
  '/admin/assets/': typeof AdminAssetsIndexRoute
  '/admin/communities/': typeof AdminCommunitiesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/communities/$slug/': typeof CommunitiesSlugIndexRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/admin/assets/$assetGroupId/assets': typeof AdminAssetsAssetGroupIdAssetsRoute
  '/admin/assets/$assetGroupId/settings': typeof AdminAssetsAssetGroupIdSettingsRoute
  '/admin/communities/$organizationId/discord': typeof AdminCommunitiesOrganizationIdDiscordRoute
  '/admin/communities/$organizationId/members': typeof AdminCommunitiesOrganizationIdMembersRoute
  '/admin/communities/$organizationId/operations': typeof AdminCommunitiesOrganizationIdOperationsRoute
  '/admin/communities/$organizationId/overview': typeof AdminCommunitiesOrganizationIdOverviewRoute
  '/admin/communities/$organizationId/roles': typeof AdminCommunitiesOrganizationIdRolesRoute
  '/admin/communities/$organizationId/settings': typeof AdminCommunitiesOrganizationIdSettingsRoute
  '/admin/users/$userId/assets': typeof AdminUsersUserIdAssetsRoute
  '/admin/users/$userId/communities': typeof AdminUsersUserIdCommunitiesRoute
  '/admin/users/$userId/identities': typeof AdminUsersUserIdIdentitiesRoute
  '/admin/users/$userId/overview': typeof AdminUsersUserIdOverviewRoute
  '/admin/users/$userId/settings': typeof AdminUsersUserIdSettingsRoute
  '/communities/$slug/collections/$address': typeof CommunitiesSlugCollectionsAddressRoute
  '/admin/assets/$assetGroupId/': typeof AdminAssetsAssetGroupIdIndexRoute
  '/admin/communities/$organizationId/': typeof AdminCommunitiesOrganizationIdIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/communities/$slug/collections/': typeof CommunitiesSlugCollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/dev/shadcn': typeof DevShadcnRoute
  '/dev/ui': typeof DevUiRoute
  '/dev/wallets': typeof DevWalletsRoute
  '/profile/assets': typeof ProfileAssetsRoute
  '/profile/identities': typeof ProfileIdentitiesRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/communities': typeof CommunitiesIndexRoute
  '/dev': typeof DevIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/admin/assets/create': typeof AdminAssetsCreateRoute
  '/communities/$slug/overview': typeof CommunitiesSlugOverviewRoute
  '/profile/$username/assets': typeof ProfileUsernameAssetsRoute
  '/profile/$username/identities': typeof ProfileUsernameIdentitiesRoute
  '/profile/$username/settings': typeof ProfileUsernameSettingsRoute
  '/admin/assets': typeof AdminAssetsIndexRoute
  '/admin/communities': typeof AdminCommunitiesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/communities/$slug': typeof CommunitiesSlugIndexRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
  '/admin/assets/$assetGroupId/assets': typeof AdminAssetsAssetGroupIdAssetsRoute
  '/admin/assets/$assetGroupId/settings': typeof AdminAssetsAssetGroupIdSettingsRoute
  '/admin/communities/$organizationId/discord': typeof AdminCommunitiesOrganizationIdDiscordRoute
  '/admin/communities/$organizationId/members': typeof AdminCommunitiesOrganizationIdMembersRoute
  '/admin/communities/$organizationId/operations': typeof AdminCommunitiesOrganizationIdOperationsRoute
  '/admin/communities/$organizationId/overview': typeof AdminCommunitiesOrganizationIdOverviewRoute
  '/admin/communities/$organizationId/roles': typeof AdminCommunitiesOrganizationIdRolesRoute
  '/admin/communities/$organizationId/settings': typeof AdminCommunitiesOrganizationIdSettingsRoute
  '/admin/users/$userId/assets': typeof AdminUsersUserIdAssetsRoute
  '/admin/users/$userId/communities': typeof AdminUsersUserIdCommunitiesRoute
  '/admin/users/$userId/identities': typeof AdminUsersUserIdIdentitiesRoute
  '/admin/users/$userId/overview': typeof AdminUsersUserIdOverviewRoute
  '/admin/users/$userId/settings': typeof AdminUsersUserIdSettingsRoute
  '/communities/$slug/collections/$address': typeof CommunitiesSlugCollectionsAddressRoute
  '/admin/assets/$assetGroupId': typeof AdminAssetsAssetGroupIdIndexRoute
  '/admin/communities/$organizationId': typeof AdminCommunitiesOrganizationIdIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdIndexRoute
  '/communities/$slug/collections': typeof CommunitiesSlugCollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/communities': typeof CommunitiesRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/dev': typeof DevRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/communities/$slug': typeof CommunitiesSlugRouteRouteWithChildren
  '/profile/$username': typeof ProfileUsernameRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/dev/shadcn': typeof DevShadcnRoute
  '/dev/ui': typeof DevUiRoute
  '/dev/wallets': typeof DevWalletsRoute
  '/profile/assets': typeof ProfileAssetsRoute
  '/profile/identities': typeof ProfileIdentitiesRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/dev/': typeof DevIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/assets/$assetGroupId': typeof AdminAssetsAssetGroupIdRouteRouteWithChildren
  '/admin/communities/$organizationId': typeof AdminCommunitiesOrganizationIdRouteRouteWithChildren
  '/admin/users/$userId': typeof AdminUsersUserIdRouteRouteWithChildren
  '/communities/$slug/collections': typeof CommunitiesSlugCollectionsRouteRouteWithChildren
  '/admin/assets/create': typeof AdminAssetsCreateRoute
  '/communities/$slug/overview': typeof CommunitiesSlugOverviewRoute
  '/profile/$username/assets': typeof ProfileUsernameAssetsRoute
  '/profile/$username/identities': typeof ProfileUsernameIdentitiesRoute
  '/profile/$username/settings': typeof ProfileUsernameSettingsRoute
  '/admin/assets/': typeof AdminAssetsIndexRoute
  '/admin/communities/': typeof AdminCommunitiesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/communities/$slug/': typeof CommunitiesSlugIndexRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/admin/assets/$assetGroupId/assets': typeof AdminAssetsAssetGroupIdAssetsRoute
  '/admin/assets/$assetGroupId/settings': typeof AdminAssetsAssetGroupIdSettingsRoute
  '/admin/communities/$organizationId/discord': typeof AdminCommunitiesOrganizationIdDiscordRoute
  '/admin/communities/$organizationId/members': typeof AdminCommunitiesOrganizationIdMembersRoute
  '/admin/communities/$organizationId/operations': typeof AdminCommunitiesOrganizationIdOperationsRoute
  '/admin/communities/$organizationId/overview': typeof AdminCommunitiesOrganizationIdOverviewRoute
  '/admin/communities/$organizationId/roles': typeof AdminCommunitiesOrganizationIdRolesRoute
  '/admin/communities/$organizationId/settings': typeof AdminCommunitiesOrganizationIdSettingsRoute
  '/admin/users/$userId/assets': typeof AdminUsersUserIdAssetsRoute
  '/admin/users/$userId/communities': typeof AdminUsersUserIdCommunitiesRoute
  '/admin/users/$userId/identities': typeof AdminUsersUserIdIdentitiesRoute
  '/admin/users/$userId/overview': typeof AdminUsersUserIdOverviewRoute
  '/admin/users/$userId/settings': typeof AdminUsersUserIdSettingsRoute
  '/communities/$slug/collections/$address': typeof CommunitiesSlugCollectionsAddressRoute
  '/admin/assets/$assetGroupId/': typeof AdminAssetsAssetGroupIdIndexRoute
  '/admin/communities/$organizationId/': typeof AdminCommunitiesOrganizationIdIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/communities/$slug/collections/': typeof CommunitiesSlugCollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/communities'
    | '/profile'
    | '/admin'
    | '/auth-callback'
    | '/dev'
    | '/login'
    | '/onboard'
    | '/communities/$slug'
    | '/profile/$username'
    | '/admin/dashboard'
    | '/dev/shadcn'
    | '/dev/ui'
    | '/dev/wallets'
    | '/profile/assets'
    | '/profile/identities'
    | '/profile/settings'
    | '/admin/'
    | '/communities/'
    | '/dev/'
    | '/profile/'
    | '/admin/assets/$assetGroupId'
    | '/admin/communities/$organizationId'
    | '/admin/users/$userId'
    | '/communities/$slug/collections'
    | '/admin/assets/create'
    | '/communities/$slug/overview'
    | '/profile/$username/assets'
    | '/profile/$username/identities'
    | '/profile/$username/settings'
    | '/admin/assets/'
    | '/admin/communities/'
    | '/admin/users/'
    | '/communities/$slug/'
    | '/profile/$username/'
    | '/admin/assets/$assetGroupId/assets'
    | '/admin/assets/$assetGroupId/settings'
    | '/admin/communities/$organizationId/discord'
    | '/admin/communities/$organizationId/members'
    | '/admin/communities/$organizationId/operations'
    | '/admin/communities/$organizationId/overview'
    | '/admin/communities/$organizationId/roles'
    | '/admin/communities/$organizationId/settings'
    | '/admin/users/$userId/assets'
    | '/admin/users/$userId/communities'
    | '/admin/users/$userId/identities'
    | '/admin/users/$userId/overview'
    | '/admin/users/$userId/settings'
    | '/communities/$slug/collections/$address'
    | '/admin/assets/$assetGroupId/'
    | '/admin/communities/$organizationId/'
    | '/admin/users/$userId/'
    | '/communities/$slug/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-callback'
    | '/login'
    | '/onboard'
    | '/admin/dashboard'
    | '/dev/shadcn'
    | '/dev/ui'
    | '/dev/wallets'
    | '/profile/assets'
    | '/profile/identities'
    | '/profile/settings'
    | '/admin'
    | '/communities'
    | '/dev'
    | '/profile'
    | '/admin/assets/create'
    | '/communities/$slug/overview'
    | '/profile/$username/assets'
    | '/profile/$username/identities'
    | '/profile/$username/settings'
    | '/admin/assets'
    | '/admin/communities'
    | '/admin/users'
    | '/communities/$slug'
    | '/profile/$username'
    | '/admin/assets/$assetGroupId/assets'
    | '/admin/assets/$assetGroupId/settings'
    | '/admin/communities/$organizationId/discord'
    | '/admin/communities/$organizationId/members'
    | '/admin/communities/$organizationId/operations'
    | '/admin/communities/$organizationId/overview'
    | '/admin/communities/$organizationId/roles'
    | '/admin/communities/$organizationId/settings'
    | '/admin/users/$userId/assets'
    | '/admin/users/$userId/communities'
    | '/admin/users/$userId/identities'
    | '/admin/users/$userId/overview'
    | '/admin/users/$userId/settings'
    | '/communities/$slug/collections/$address'
    | '/admin/assets/$assetGroupId'
    | '/admin/communities/$organizationId'
    | '/admin/users/$userId'
    | '/communities/$slug/collections'
  id:
    | '__root__'
    | '/'
    | '/communities'
    | '/profile'
    | '/admin'
    | '/auth-callback'
    | '/dev'
    | '/login'
    | '/onboard'
    | '/communities/$slug'
    | '/profile/$username'
    | '/admin/dashboard'
    | '/dev/shadcn'
    | '/dev/ui'
    | '/dev/wallets'
    | '/profile/assets'
    | '/profile/identities'
    | '/profile/settings'
    | '/admin/'
    | '/communities/'
    | '/dev/'
    | '/profile/'
    | '/admin/assets/$assetGroupId'
    | '/admin/communities/$organizationId'
    | '/admin/users/$userId'
    | '/communities/$slug/collections'
    | '/admin/assets/create'
    | '/communities/$slug/overview'
    | '/profile/$username/assets'
    | '/profile/$username/identities'
    | '/profile/$username/settings'
    | '/admin/assets/'
    | '/admin/communities/'
    | '/admin/users/'
    | '/communities/$slug/'
    | '/profile/$username/'
    | '/admin/assets/$assetGroupId/assets'
    | '/admin/assets/$assetGroupId/settings'
    | '/admin/communities/$organizationId/discord'
    | '/admin/communities/$organizationId/members'
    | '/admin/communities/$organizationId/operations'
    | '/admin/communities/$organizationId/overview'
    | '/admin/communities/$organizationId/roles'
    | '/admin/communities/$organizationId/settings'
    | '/admin/users/$userId/assets'
    | '/admin/users/$userId/communities'
    | '/admin/users/$userId/identities'
    | '/admin/users/$userId/overview'
    | '/admin/users/$userId/settings'
    | '/communities/$slug/collections/$address'
    | '/admin/assets/$assetGroupId/'
    | '/admin/communities/$organizationId/'
    | '/admin/users/$userId/'
    | '/communities/$slug/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunitiesRouteRoute: typeof CommunitiesRouteRouteWithChildren
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  DevRoute: typeof DevRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRoute
    }
    '/communities/': {
      id: '/communities/'
      path: '/'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof CommunitiesRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/identities': {
      id: '/profile/identities'
      path: '/identities'
      fullPath: '/profile/identities'
      preLoaderRoute: typeof ProfileIdentitiesRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/assets': {
      id: '/profile/assets'
      path: '/assets'
      fullPath: '/profile/assets'
      preLoaderRoute: typeof ProfileAssetsRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/dev/wallets': {
      id: '/dev/wallets'
      path: '/wallets'
      fullPath: '/dev/wallets'
      preLoaderRoute: typeof DevWalletsRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/shadcn': {
      id: '/dev/shadcn'
      path: '/shadcn'
      fullPath: '/dev/shadcn'
      preLoaderRoute: typeof DevShadcnRouteImport
      parentRoute: typeof DevRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/communities/$slug': {
      id: '/communities/$slug'
      path: '/$slug'
      fullPath: '/communities/$slug'
      preLoaderRoute: typeof CommunitiesSlugRouteRouteImport
      parentRoute: typeof CommunitiesRouteRoute
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof ProfileUsernameIndexRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/communities/$slug/': {
      id: '/communities/$slug/'
      path: '/'
      fullPath: '/communities/$slug/'
      preLoaderRoute: typeof CommunitiesSlugIndexRouteImport
      parentRoute: typeof CommunitiesSlugRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communities/': {
      id: '/admin/communities/'
      path: '/communities'
      fullPath: '/admin/communities/'
      preLoaderRoute: typeof AdminCommunitiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/': {
      id: '/admin/assets/'
      path: '/assets'
      fullPath: '/admin/assets/'
      preLoaderRoute: typeof AdminAssetsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/$username/settings': {
      id: '/profile/$username/settings'
      path: '/settings'
      fullPath: '/profile/$username/settings'
      preLoaderRoute: typeof ProfileUsernameSettingsRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/identities': {
      id: '/profile/$username/identities'
      path: '/identities'
      fullPath: '/profile/$username/identities'
      preLoaderRoute: typeof ProfileUsernameIdentitiesRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/assets': {
      id: '/profile/$username/assets'
      path: '/assets'
      fullPath: '/profile/$username/assets'
      preLoaderRoute: typeof ProfileUsernameAssetsRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/communities/$slug/overview': {
      id: '/communities/$slug/overview'
      path: '/overview'
      fullPath: '/communities/$slug/overview'
      preLoaderRoute: typeof CommunitiesSlugOverviewRouteImport
      parentRoute: typeof CommunitiesSlugRouteRoute
    }
    '/admin/assets/create': {
      id: '/admin/assets/create'
      path: '/assets/create'
      fullPath: '/admin/assets/create'
      preLoaderRoute: typeof AdminAssetsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/communities/$slug/collections': {
      id: '/communities/$slug/collections'
      path: '/collections'
      fullPath: '/communities/$slug/collections'
      preLoaderRoute: typeof CommunitiesSlugCollectionsRouteRouteImport
      parentRoute: typeof CommunitiesSlugRouteRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communities/$organizationId': {
      id: '/admin/communities/$organizationId'
      path: '/communities/$organizationId'
      fullPath: '/admin/communities/$organizationId'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdRouteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/$assetGroupId': {
      id: '/admin/assets/$assetGroupId'
      path: '/assets/$assetGroupId'
      fullPath: '/admin/assets/$assetGroupId'
      preLoaderRoute: typeof AdminAssetsAssetGroupIdRouteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/communities/$slug/collections/': {
      id: '/communities/$slug/collections/'
      path: '/'
      fullPath: '/communities/$slug/collections/'
      preLoaderRoute: typeof CommunitiesSlugCollectionsIndexRouteImport
      parentRoute: typeof CommunitiesSlugCollectionsRouteRoute
    }
    '/admin/users/$userId/': {
      id: '/admin/users/$userId/'
      path: '/'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AdminUsersUserIdIndexRouteImport
      parentRoute: typeof AdminUsersUserIdRouteRoute
    }
    '/admin/communities/$organizationId/': {
      id: '/admin/communities/$organizationId/'
      path: '/'
      fullPath: '/admin/communities/$organizationId/'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdIndexRouteImport
      parentRoute: typeof AdminCommunitiesOrganizationIdRouteRoute
    }
    '/admin/assets/$assetGroupId/': {
      id: '/admin/assets/$assetGroupId/'
      path: '/'
      fullPath: '/admin/assets/$assetGroupId/'
      preLoaderRoute: typeof AdminAssetsAssetGroupIdIndexRouteImport
      parentRoute: typeof AdminAssetsAssetGroupIdRouteRoute
    }
    '/communities/$slug/collections/$address': {
      id: '/communities/$slug/collections/$address'
      path: '/$address'
      fullPath: '/communities/$slug/collections/$address'
      preLoaderRoute: typeof CommunitiesSlugCollectionsAddressRouteImport
      parentRoute: typeof CommunitiesSlugCollectionsRouteRoute
    }
    '/admin/users/$userId/settings': {
      id: '/admin/users/$userId/settings'
      path: '/settings'
      fullPath: '/admin/users/$userId/settings'
      preLoaderRoute: typeof AdminUsersUserIdSettingsRouteImport
      parentRoute: typeof AdminUsersUserIdRouteRoute
    }
    '/admin/users/$userId/overview': {
      id: '/admin/users/$userId/overview'
      path: '/overview'
      fullPath: '/admin/users/$userId/overview'
      preLoaderRoute: typeof AdminUsersUserIdOverviewRouteImport
      parentRoute: typeof AdminUsersUserIdRouteRoute
    }
    '/admin/users/$userId/identities': {
      id: '/admin/users/$userId/identities'
      path: '/identities'
      fullPath: '/admin/users/$userId/identities'
      preLoaderRoute: typeof AdminUsersUserIdIdentitiesRouteImport
      parentRoute: typeof AdminUsersUserIdRouteRoute
    }
    '/admin/users/$userId/communities': {
      id: '/admin/users/$userId/communities'
      path: '/communities'
      fullPath: '/admin/users/$userId/communities'
      preLoaderRoute: typeof AdminUsersUserIdCommunitiesRouteImport
      parentRoute: typeof AdminUsersUserIdRouteRoute
    }
    '/admin/users/$userId/assets': {
      id: '/admin/users/$userId/assets'
      path: '/assets'
      fullPath: '/admin/users/$userId/assets'
      preLoaderRoute: typeof AdminUsersUserIdAssetsRouteImport
      parentRoute: typeof AdminUsersUserIdRouteRoute
    }
    '/admin/communities/$organizationId/settings': {
      id: '/admin/communities/$organizationId/settings'
      path: '/settings'
      fullPath: '/admin/communities/$organizationId/settings'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdSettingsRouteImport
      parentRoute: typeof AdminCommunitiesOrganizationIdRouteRoute
    }
    '/admin/communities/$organizationId/roles': {
      id: '/admin/communities/$organizationId/roles'
      path: '/roles'
      fullPath: '/admin/communities/$organizationId/roles'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdRolesRouteImport
      parentRoute: typeof AdminCommunitiesOrganizationIdRouteRoute
    }
    '/admin/communities/$organizationId/overview': {
      id: '/admin/communities/$organizationId/overview'
      path: '/overview'
      fullPath: '/admin/communities/$organizationId/overview'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdOverviewRouteImport
      parentRoute: typeof AdminCommunitiesOrganizationIdRouteRoute
    }
    '/admin/communities/$organizationId/operations': {
      id: '/admin/communities/$organizationId/operations'
      path: '/operations'
      fullPath: '/admin/communities/$organizationId/operations'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdOperationsRouteImport
      parentRoute: typeof AdminCommunitiesOrganizationIdRouteRoute
    }
    '/admin/communities/$organizationId/members': {
      id: '/admin/communities/$organizationId/members'
      path: '/members'
      fullPath: '/admin/communities/$organizationId/members'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdMembersRouteImport
      parentRoute: typeof AdminCommunitiesOrganizationIdRouteRoute
    }
    '/admin/communities/$organizationId/discord': {
      id: '/admin/communities/$organizationId/discord'
      path: '/discord'
      fullPath: '/admin/communities/$organizationId/discord'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdDiscordRouteImport
      parentRoute: typeof AdminCommunitiesOrganizationIdRouteRoute
    }
    '/admin/assets/$assetGroupId/settings': {
      id: '/admin/assets/$assetGroupId/settings'
      path: '/settings'
      fullPath: '/admin/assets/$assetGroupId/settings'
      preLoaderRoute: typeof AdminAssetsAssetGroupIdSettingsRouteImport
      parentRoute: typeof AdminAssetsAssetGroupIdRouteRoute
    }
    '/admin/assets/$assetGroupId/assets': {
      id: '/admin/assets/$assetGroupId/assets'
      path: '/assets'
      fullPath: '/admin/assets/$assetGroupId/assets'
      preLoaderRoute: typeof AdminAssetsAssetGroupIdAssetsRouteImport
      parentRoute: typeof AdminAssetsAssetGroupIdRouteRoute
    }
  }
}

interface CommunitiesSlugCollectionsRouteRouteChildren {
  CommunitiesSlugCollectionsAddressRoute: typeof CommunitiesSlugCollectionsAddressRoute
  CommunitiesSlugCollectionsIndexRoute: typeof CommunitiesSlugCollectionsIndexRoute
}

const CommunitiesSlugCollectionsRouteRouteChildren: CommunitiesSlugCollectionsRouteRouteChildren =
  {
    CommunitiesSlugCollectionsAddressRoute:
      CommunitiesSlugCollectionsAddressRoute,
    CommunitiesSlugCollectionsIndexRoute: CommunitiesSlugCollectionsIndexRoute,
  }

const CommunitiesSlugCollectionsRouteRouteWithChildren =
  CommunitiesSlugCollectionsRouteRoute._addFileChildren(
    CommunitiesSlugCollectionsRouteRouteChildren,
  )

interface CommunitiesSlugRouteRouteChildren {
  CommunitiesSlugCollectionsRouteRoute: typeof CommunitiesSlugCollectionsRouteRouteWithChildren
  CommunitiesSlugOverviewRoute: typeof CommunitiesSlugOverviewRoute
  CommunitiesSlugIndexRoute: typeof CommunitiesSlugIndexRoute
}

const CommunitiesSlugRouteRouteChildren: CommunitiesSlugRouteRouteChildren = {
  CommunitiesSlugCollectionsRouteRoute:
    CommunitiesSlugCollectionsRouteRouteWithChildren,
  CommunitiesSlugOverviewRoute: CommunitiesSlugOverviewRoute,
  CommunitiesSlugIndexRoute: CommunitiesSlugIndexRoute,
}

const CommunitiesSlugRouteRouteWithChildren =
  CommunitiesSlugRouteRoute._addFileChildren(CommunitiesSlugRouteRouteChildren)

interface CommunitiesRouteRouteChildren {
  CommunitiesSlugRouteRoute: typeof CommunitiesSlugRouteRouteWithChildren
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
}

const CommunitiesRouteRouteChildren: CommunitiesRouteRouteChildren = {
  CommunitiesSlugRouteRoute: CommunitiesSlugRouteRouteWithChildren,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
}

const CommunitiesRouteRouteWithChildren =
  CommunitiesRouteRoute._addFileChildren(CommunitiesRouteRouteChildren)

interface ProfileUsernameRouteRouteChildren {
  ProfileUsernameAssetsRoute: typeof ProfileUsernameAssetsRoute
  ProfileUsernameIdentitiesRoute: typeof ProfileUsernameIdentitiesRoute
  ProfileUsernameSettingsRoute: typeof ProfileUsernameSettingsRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
}

const ProfileUsernameRouteRouteChildren: ProfileUsernameRouteRouteChildren = {
  ProfileUsernameAssetsRoute: ProfileUsernameAssetsRoute,
  ProfileUsernameIdentitiesRoute: ProfileUsernameIdentitiesRoute,
  ProfileUsernameSettingsRoute: ProfileUsernameSettingsRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
}

const ProfileUsernameRouteRouteWithChildren =
  ProfileUsernameRouteRoute._addFileChildren(ProfileUsernameRouteRouteChildren)

interface ProfileRouteRouteChildren {
  ProfileUsernameRouteRoute: typeof ProfileUsernameRouteRouteWithChildren
  ProfileAssetsRoute: typeof ProfileAssetsRoute
  ProfileIdentitiesRoute: typeof ProfileIdentitiesRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileUsernameRouteRoute: ProfileUsernameRouteRouteWithChildren,
  ProfileAssetsRoute: ProfileAssetsRoute,
  ProfileIdentitiesRoute: ProfileIdentitiesRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

interface AdminAssetsAssetGroupIdRouteRouteChildren {
  AdminAssetsAssetGroupIdAssetsRoute: typeof AdminAssetsAssetGroupIdAssetsRoute
  AdminAssetsAssetGroupIdSettingsRoute: typeof AdminAssetsAssetGroupIdSettingsRoute
  AdminAssetsAssetGroupIdIndexRoute: typeof AdminAssetsAssetGroupIdIndexRoute
}

const AdminAssetsAssetGroupIdRouteRouteChildren: AdminAssetsAssetGroupIdRouteRouteChildren =
  {
    AdminAssetsAssetGroupIdAssetsRoute: AdminAssetsAssetGroupIdAssetsRoute,
    AdminAssetsAssetGroupIdSettingsRoute: AdminAssetsAssetGroupIdSettingsRoute,
    AdminAssetsAssetGroupIdIndexRoute: AdminAssetsAssetGroupIdIndexRoute,
  }

const AdminAssetsAssetGroupIdRouteRouteWithChildren =
  AdminAssetsAssetGroupIdRouteRoute._addFileChildren(
    AdminAssetsAssetGroupIdRouteRouteChildren,
  )

interface AdminCommunitiesOrganizationIdRouteRouteChildren {
  AdminCommunitiesOrganizationIdDiscordRoute: typeof AdminCommunitiesOrganizationIdDiscordRoute
  AdminCommunitiesOrganizationIdMembersRoute: typeof AdminCommunitiesOrganizationIdMembersRoute
  AdminCommunitiesOrganizationIdOperationsRoute: typeof AdminCommunitiesOrganizationIdOperationsRoute
  AdminCommunitiesOrganizationIdOverviewRoute: typeof AdminCommunitiesOrganizationIdOverviewRoute
  AdminCommunitiesOrganizationIdRolesRoute: typeof AdminCommunitiesOrganizationIdRolesRoute
  AdminCommunitiesOrganizationIdSettingsRoute: typeof AdminCommunitiesOrganizationIdSettingsRoute
  AdminCommunitiesOrganizationIdIndexRoute: typeof AdminCommunitiesOrganizationIdIndexRoute
}

const AdminCommunitiesOrganizationIdRouteRouteChildren: AdminCommunitiesOrganizationIdRouteRouteChildren =
  {
    AdminCommunitiesOrganizationIdDiscordRoute:
      AdminCommunitiesOrganizationIdDiscordRoute,
    AdminCommunitiesOrganizationIdMembersRoute:
      AdminCommunitiesOrganizationIdMembersRoute,
    AdminCommunitiesOrganizationIdOperationsRoute:
      AdminCommunitiesOrganizationIdOperationsRoute,
    AdminCommunitiesOrganizationIdOverviewRoute:
      AdminCommunitiesOrganizationIdOverviewRoute,
    AdminCommunitiesOrganizationIdRolesRoute:
      AdminCommunitiesOrganizationIdRolesRoute,
    AdminCommunitiesOrganizationIdSettingsRoute:
      AdminCommunitiesOrganizationIdSettingsRoute,
    AdminCommunitiesOrganizationIdIndexRoute:
      AdminCommunitiesOrganizationIdIndexRoute,
  }

const AdminCommunitiesOrganizationIdRouteRouteWithChildren =
  AdminCommunitiesOrganizationIdRouteRoute._addFileChildren(
    AdminCommunitiesOrganizationIdRouteRouteChildren,
  )

interface AdminUsersUserIdRouteRouteChildren {
  AdminUsersUserIdAssetsRoute: typeof AdminUsersUserIdAssetsRoute
  AdminUsersUserIdCommunitiesRoute: typeof AdminUsersUserIdCommunitiesRoute
  AdminUsersUserIdIdentitiesRoute: typeof AdminUsersUserIdIdentitiesRoute
  AdminUsersUserIdOverviewRoute: typeof AdminUsersUserIdOverviewRoute
  AdminUsersUserIdSettingsRoute: typeof AdminUsersUserIdSettingsRoute
  AdminUsersUserIdIndexRoute: typeof AdminUsersUserIdIndexRoute
}

const AdminUsersUserIdRouteRouteChildren: AdminUsersUserIdRouteRouteChildren = {
  AdminUsersUserIdAssetsRoute: AdminUsersUserIdAssetsRoute,
  AdminUsersUserIdCommunitiesRoute: AdminUsersUserIdCommunitiesRoute,
  AdminUsersUserIdIdentitiesRoute: AdminUsersUserIdIdentitiesRoute,
  AdminUsersUserIdOverviewRoute: AdminUsersUserIdOverviewRoute,
  AdminUsersUserIdSettingsRoute: AdminUsersUserIdSettingsRoute,
  AdminUsersUserIdIndexRoute: AdminUsersUserIdIndexRoute,
}

const AdminUsersUserIdRouteRouteWithChildren =
  AdminUsersUserIdRouteRoute._addFileChildren(
    AdminUsersUserIdRouteRouteChildren,
  )

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAssetsAssetGroupIdRouteRoute: typeof AdminAssetsAssetGroupIdRouteRouteWithChildren
  AdminCommunitiesOrganizationIdRouteRoute: typeof AdminCommunitiesOrganizationIdRouteRouteWithChildren
  AdminUsersUserIdRouteRoute: typeof AdminUsersUserIdRouteRouteWithChildren
  AdminAssetsCreateRoute: typeof AdminAssetsCreateRoute
  AdminAssetsIndexRoute: typeof AdminAssetsIndexRoute
  AdminCommunitiesIndexRoute: typeof AdminCommunitiesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAssetsAssetGroupIdRouteRoute:
    AdminAssetsAssetGroupIdRouteRouteWithChildren,
  AdminCommunitiesOrganizationIdRouteRoute:
    AdminCommunitiesOrganizationIdRouteRouteWithChildren,
  AdminUsersUserIdRouteRoute: AdminUsersUserIdRouteRouteWithChildren,
  AdminAssetsCreateRoute: AdminAssetsCreateRoute,
  AdminAssetsIndexRoute: AdminAssetsIndexRoute,
  AdminCommunitiesIndexRoute: AdminCommunitiesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DevRouteChildren {
  DevShadcnRoute: typeof DevShadcnRoute
  DevUiRoute: typeof DevUiRoute
  DevWalletsRoute: typeof DevWalletsRoute
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevShadcnRoute: DevShadcnRoute,
  DevUiRoute: DevUiRoute,
  DevWalletsRoute: DevWalletsRoute,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunitiesRouteRoute: CommunitiesRouteRouteWithChildren,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  DevRoute: DevRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
