/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCommunitiesIndexRouteImport } from './routes/admin/communities/index'
import { Route as AdminAssetsIndexRouteImport } from './routes/admin/assets/index'
import { Route as AdminAssetsCreateRouteImport } from './routes/admin/assets/create'
import { Route as AdminCommunitiesOrganizationIdRouteRouteImport } from './routes/admin/communities/$organizationId/route'
import { Route as AdminAssetsAssetGroupIdRouteRouteImport } from './routes/admin/assets/$assetGroupId/route'
import { Route as AdminCommunitiesOrganizationIdIndexRouteImport } from './routes/admin/communities/$organizationId/index'
import { Route as AdminAssetsAssetGroupIdIndexRouteImport } from './routes/admin/assets/$assetGroupId/index'
import { Route as AdminCommunitiesOrganizationIdSettingsRouteImport } from './routes/admin/communities/$organizationId/settings'
import { Route as AdminCommunitiesOrganizationIdRolesRouteImport } from './routes/admin/communities/$organizationId/roles'
import { Route as AdminCommunitiesOrganizationIdMembersRouteImport } from './routes/admin/communities/$organizationId/members'
import { Route as AdminAssetsAssetGroupIdSettingsRouteImport } from './routes/admin/assets/$assetGroupId/settings'
import { Route as AdminAssetsAssetGroupIdAssetsRouteImport } from './routes/admin/assets/$assetGroupId/assets'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunitiesIndexRoute = AdminCommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsIndexRoute = AdminAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsCreateRoute = AdminAssetsCreateRouteImport.update({
  id: '/assets/create',
  path: '/assets/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunitiesOrganizationIdRouteRoute =
  AdminCommunitiesOrganizationIdRouteRouteImport.update({
    id: '/communities/$organizationId',
    path: '/communities/$organizationId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAssetsAssetGroupIdRouteRoute =
  AdminAssetsAssetGroupIdRouteRouteImport.update({
    id: '/assets/$assetGroupId',
    path: '/assets/$assetGroupId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCommunitiesOrganizationIdIndexRoute =
  AdminCommunitiesOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminCommunitiesOrganizationIdRouteRoute,
  } as any)
const AdminAssetsAssetGroupIdIndexRoute =
  AdminAssetsAssetGroupIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAssetsAssetGroupIdRouteRoute,
  } as any)
const AdminCommunitiesOrganizationIdSettingsRoute =
  AdminCommunitiesOrganizationIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminCommunitiesOrganizationIdRouteRoute,
  } as any)
const AdminCommunitiesOrganizationIdRolesRoute =
  AdminCommunitiesOrganizationIdRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AdminCommunitiesOrganizationIdRouteRoute,
  } as any)
const AdminCommunitiesOrganizationIdMembersRoute =
  AdminCommunitiesOrganizationIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AdminCommunitiesOrganizationIdRouteRoute,
  } as any)
const AdminAssetsAssetGroupIdSettingsRoute =
  AdminAssetsAssetGroupIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminAssetsAssetGroupIdRouteRoute,
  } as any)
const AdminAssetsAssetGroupIdAssetsRoute =
  AdminAssetsAssetGroupIdAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AdminAssetsAssetGroupIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/assets/$assetGroupId': typeof AdminAssetsAssetGroupIdRouteRouteWithChildren
  '/admin/communities/$organizationId': typeof AdminCommunitiesOrganizationIdRouteRouteWithChildren
  '/admin/assets/create': typeof AdminAssetsCreateRoute
  '/admin/assets/': typeof AdminAssetsIndexRoute
  '/admin/communities/': typeof AdminCommunitiesIndexRoute
  '/admin/assets/$assetGroupId/assets': typeof AdminAssetsAssetGroupIdAssetsRoute
  '/admin/assets/$assetGroupId/settings': typeof AdminAssetsAssetGroupIdSettingsRoute
  '/admin/communities/$organizationId/members': typeof AdminCommunitiesOrganizationIdMembersRoute
  '/admin/communities/$organizationId/roles': typeof AdminCommunitiesOrganizationIdRolesRoute
  '/admin/communities/$organizationId/settings': typeof AdminCommunitiesOrganizationIdSettingsRoute
  '/admin/assets/$assetGroupId/': typeof AdminAssetsAssetGroupIdIndexRoute
  '/admin/communities/$organizationId/': typeof AdminCommunitiesOrganizationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/admin/assets/create': typeof AdminAssetsCreateRoute
  '/admin/assets': typeof AdminAssetsIndexRoute
  '/admin/communities': typeof AdminCommunitiesIndexRoute
  '/admin/assets/$assetGroupId/assets': typeof AdminAssetsAssetGroupIdAssetsRoute
  '/admin/assets/$assetGroupId/settings': typeof AdminAssetsAssetGroupIdSettingsRoute
  '/admin/communities/$organizationId/members': typeof AdminCommunitiesOrganizationIdMembersRoute
  '/admin/communities/$organizationId/roles': typeof AdminCommunitiesOrganizationIdRolesRoute
  '/admin/communities/$organizationId/settings': typeof AdminCommunitiesOrganizationIdSettingsRoute
  '/admin/assets/$assetGroupId': typeof AdminAssetsAssetGroupIdIndexRoute
  '/admin/communities/$organizationId': typeof AdminCommunitiesOrganizationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/assets/$assetGroupId': typeof AdminAssetsAssetGroupIdRouteRouteWithChildren
  '/admin/communities/$organizationId': typeof AdminCommunitiesOrganizationIdRouteRouteWithChildren
  '/admin/assets/create': typeof AdminAssetsCreateRoute
  '/admin/assets/': typeof AdminAssetsIndexRoute
  '/admin/communities/': typeof AdminCommunitiesIndexRoute
  '/admin/assets/$assetGroupId/assets': typeof AdminAssetsAssetGroupIdAssetsRoute
  '/admin/assets/$assetGroupId/settings': typeof AdminAssetsAssetGroupIdSettingsRoute
  '/admin/communities/$organizationId/members': typeof AdminCommunitiesOrganizationIdMembersRoute
  '/admin/communities/$organizationId/roles': typeof AdminCommunitiesOrganizationIdRolesRoute
  '/admin/communities/$organizationId/settings': typeof AdminCommunitiesOrganizationIdSettingsRoute
  '/admin/assets/$assetGroupId/': typeof AdminAssetsAssetGroupIdIndexRoute
  '/admin/communities/$organizationId/': typeof AdminCommunitiesOrganizationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth-callback'
    | '/login'
    | '/onboard'
    | '/profile'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/assets/$assetGroupId'
    | '/admin/communities/$organizationId'
    | '/admin/assets/create'
    | '/admin/assets/'
    | '/admin/communities/'
    | '/admin/assets/$assetGroupId/assets'
    | '/admin/assets/$assetGroupId/settings'
    | '/admin/communities/$organizationId/members'
    | '/admin/communities/$organizationId/roles'
    | '/admin/communities/$organizationId/settings'
    | '/admin/assets/$assetGroupId/'
    | '/admin/communities/$organizationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-callback'
    | '/login'
    | '/onboard'
    | '/profile'
    | '/admin/dashboard'
    | '/admin'
    | '/admin/assets/create'
    | '/admin/assets'
    | '/admin/communities'
    | '/admin/assets/$assetGroupId/assets'
    | '/admin/assets/$assetGroupId/settings'
    | '/admin/communities/$organizationId/members'
    | '/admin/communities/$organizationId/roles'
    | '/admin/communities/$organizationId/settings'
    | '/admin/assets/$assetGroupId'
    | '/admin/communities/$organizationId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth-callback'
    | '/login'
    | '/onboard'
    | '/profile'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/assets/$assetGroupId'
    | '/admin/communities/$organizationId'
    | '/admin/assets/create'
    | '/admin/assets/'
    | '/admin/communities/'
    | '/admin/assets/$assetGroupId/assets'
    | '/admin/assets/$assetGroupId/settings'
    | '/admin/communities/$organizationId/members'
    | '/admin/communities/$organizationId/roles'
    | '/admin/communities/$organizationId/settings'
    | '/admin/assets/$assetGroupId/'
    | '/admin/communities/$organizationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communities/': {
      id: '/admin/communities/'
      path: '/communities'
      fullPath: '/admin/communities/'
      preLoaderRoute: typeof AdminCommunitiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/': {
      id: '/admin/assets/'
      path: '/assets'
      fullPath: '/admin/assets/'
      preLoaderRoute: typeof AdminAssetsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/create': {
      id: '/admin/assets/create'
      path: '/assets/create'
      fullPath: '/admin/assets/create'
      preLoaderRoute: typeof AdminAssetsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communities/$organizationId': {
      id: '/admin/communities/$organizationId'
      path: '/communities/$organizationId'
      fullPath: '/admin/communities/$organizationId'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdRouteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/$assetGroupId': {
      id: '/admin/assets/$assetGroupId'
      path: '/assets/$assetGroupId'
      fullPath: '/admin/assets/$assetGroupId'
      preLoaderRoute: typeof AdminAssetsAssetGroupIdRouteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communities/$organizationId/': {
      id: '/admin/communities/$organizationId/'
      path: '/'
      fullPath: '/admin/communities/$organizationId/'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdIndexRouteImport
      parentRoute: typeof AdminCommunitiesOrganizationIdRouteRoute
    }
    '/admin/assets/$assetGroupId/': {
      id: '/admin/assets/$assetGroupId/'
      path: '/'
      fullPath: '/admin/assets/$assetGroupId/'
      preLoaderRoute: typeof AdminAssetsAssetGroupIdIndexRouteImport
      parentRoute: typeof AdminAssetsAssetGroupIdRouteRoute
    }
    '/admin/communities/$organizationId/settings': {
      id: '/admin/communities/$organizationId/settings'
      path: '/settings'
      fullPath: '/admin/communities/$organizationId/settings'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdSettingsRouteImport
      parentRoute: typeof AdminCommunitiesOrganizationIdRouteRoute
    }
    '/admin/communities/$organizationId/roles': {
      id: '/admin/communities/$organizationId/roles'
      path: '/roles'
      fullPath: '/admin/communities/$organizationId/roles'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdRolesRouteImport
      parentRoute: typeof AdminCommunitiesOrganizationIdRouteRoute
    }
    '/admin/communities/$organizationId/members': {
      id: '/admin/communities/$organizationId/members'
      path: '/members'
      fullPath: '/admin/communities/$organizationId/members'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdMembersRouteImport
      parentRoute: typeof AdminCommunitiesOrganizationIdRouteRoute
    }
    '/admin/assets/$assetGroupId/settings': {
      id: '/admin/assets/$assetGroupId/settings'
      path: '/settings'
      fullPath: '/admin/assets/$assetGroupId/settings'
      preLoaderRoute: typeof AdminAssetsAssetGroupIdSettingsRouteImport
      parentRoute: typeof AdminAssetsAssetGroupIdRouteRoute
    }
    '/admin/assets/$assetGroupId/assets': {
      id: '/admin/assets/$assetGroupId/assets'
      path: '/assets'
      fullPath: '/admin/assets/$assetGroupId/assets'
      preLoaderRoute: typeof AdminAssetsAssetGroupIdAssetsRouteImport
      parentRoute: typeof AdminAssetsAssetGroupIdRouteRoute
    }
  }
}

interface AdminAssetsAssetGroupIdRouteRouteChildren {
  AdminAssetsAssetGroupIdAssetsRoute: typeof AdminAssetsAssetGroupIdAssetsRoute
  AdminAssetsAssetGroupIdSettingsRoute: typeof AdminAssetsAssetGroupIdSettingsRoute
  AdminAssetsAssetGroupIdIndexRoute: typeof AdminAssetsAssetGroupIdIndexRoute
}

const AdminAssetsAssetGroupIdRouteRouteChildren: AdminAssetsAssetGroupIdRouteRouteChildren =
  {
    AdminAssetsAssetGroupIdAssetsRoute: AdminAssetsAssetGroupIdAssetsRoute,
    AdminAssetsAssetGroupIdSettingsRoute: AdminAssetsAssetGroupIdSettingsRoute,
    AdminAssetsAssetGroupIdIndexRoute: AdminAssetsAssetGroupIdIndexRoute,
  }

const AdminAssetsAssetGroupIdRouteRouteWithChildren =
  AdminAssetsAssetGroupIdRouteRoute._addFileChildren(
    AdminAssetsAssetGroupIdRouteRouteChildren,
  )

interface AdminCommunitiesOrganizationIdRouteRouteChildren {
  AdminCommunitiesOrganizationIdMembersRoute: typeof AdminCommunitiesOrganizationIdMembersRoute
  AdminCommunitiesOrganizationIdRolesRoute: typeof AdminCommunitiesOrganizationIdRolesRoute
  AdminCommunitiesOrganizationIdSettingsRoute: typeof AdminCommunitiesOrganizationIdSettingsRoute
  AdminCommunitiesOrganizationIdIndexRoute: typeof AdminCommunitiesOrganizationIdIndexRoute
}

const AdminCommunitiesOrganizationIdRouteRouteChildren: AdminCommunitiesOrganizationIdRouteRouteChildren =
  {
    AdminCommunitiesOrganizationIdMembersRoute:
      AdminCommunitiesOrganizationIdMembersRoute,
    AdminCommunitiesOrganizationIdRolesRoute:
      AdminCommunitiesOrganizationIdRolesRoute,
    AdminCommunitiesOrganizationIdSettingsRoute:
      AdminCommunitiesOrganizationIdSettingsRoute,
    AdminCommunitiesOrganizationIdIndexRoute:
      AdminCommunitiesOrganizationIdIndexRoute,
  }

const AdminCommunitiesOrganizationIdRouteRouteWithChildren =
  AdminCommunitiesOrganizationIdRouteRoute._addFileChildren(
    AdminCommunitiesOrganizationIdRouteRouteChildren,
  )

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAssetsAssetGroupIdRouteRoute: typeof AdminAssetsAssetGroupIdRouteRouteWithChildren
  AdminCommunitiesOrganizationIdRouteRoute: typeof AdminCommunitiesOrganizationIdRouteRouteWithChildren
  AdminAssetsCreateRoute: typeof AdminAssetsCreateRoute
  AdminAssetsIndexRoute: typeof AdminAssetsIndexRoute
  AdminCommunitiesIndexRoute: typeof AdminCommunitiesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAssetsAssetGroupIdRouteRoute:
    AdminAssetsAssetGroupIdRouteRouteWithChildren,
  AdminCommunitiesOrganizationIdRouteRoute:
    AdminCommunitiesOrganizationIdRouteRouteWithChildren,
  AdminAssetsCreateRoute: AdminAssetsCreateRoute,
  AdminAssetsIndexRoute: AdminAssetsIndexRoute,
  AdminCommunitiesIndexRoute: AdminCommunitiesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
