/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCommunitiesIndexRouteImport } from './routes/admin/communities/index'
import { Route as AdminCommunitiesOrganizationIdRouteRouteImport } from './routes/admin/communities/$organizationId/route'
import { Route as AdminCommunitiesOrganizationIdIndexRouteImport } from './routes/admin/communities/$organizationId/index'
import { Route as AdminCommunitiesOrganizationIdSettingsRouteImport } from './routes/admin/communities/$organizationId/settings'
import { Route as AdminCommunitiesOrganizationIdMembersRouteImport } from './routes/admin/communities/$organizationId/members'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunitiesIndexRoute = AdminCommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunitiesOrganizationIdRouteRoute =
  AdminCommunitiesOrganizationIdRouteRouteImport.update({
    id: '/communities/$organizationId',
    path: '/communities/$organizationId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCommunitiesOrganizationIdIndexRoute =
  AdminCommunitiesOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminCommunitiesOrganizationIdRouteRoute,
  } as any)
const AdminCommunitiesOrganizationIdSettingsRoute =
  AdminCommunitiesOrganizationIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminCommunitiesOrganizationIdRouteRoute,
  } as any)
const AdminCommunitiesOrganizationIdMembersRoute =
  AdminCommunitiesOrganizationIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AdminCommunitiesOrganizationIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/communities/$organizationId': typeof AdminCommunitiesOrganizationIdRouteRouteWithChildren
  '/admin/communities/': typeof AdminCommunitiesIndexRoute
  '/admin/communities/$organizationId/members': typeof AdminCommunitiesOrganizationIdMembersRoute
  '/admin/communities/$organizationId/settings': typeof AdminCommunitiesOrganizationIdSettingsRoute
  '/admin/communities/$organizationId/': typeof AdminCommunitiesOrganizationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/admin/communities': typeof AdminCommunitiesIndexRoute
  '/admin/communities/$organizationId/members': typeof AdminCommunitiesOrganizationIdMembersRoute
  '/admin/communities/$organizationId/settings': typeof AdminCommunitiesOrganizationIdSettingsRoute
  '/admin/communities/$organizationId': typeof AdminCommunitiesOrganizationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/profile': typeof ProfileRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/communities/$organizationId': typeof AdminCommunitiesOrganizationIdRouteRouteWithChildren
  '/admin/communities/': typeof AdminCommunitiesIndexRoute
  '/admin/communities/$organizationId/members': typeof AdminCommunitiesOrganizationIdMembersRoute
  '/admin/communities/$organizationId/settings': typeof AdminCommunitiesOrganizationIdSettingsRoute
  '/admin/communities/$organizationId/': typeof AdminCommunitiesOrganizationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/onboard'
    | '/profile'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/communities/$organizationId'
    | '/admin/communities/'
    | '/admin/communities/$organizationId/members'
    | '/admin/communities/$organizationId/settings'
    | '/admin/communities/$organizationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboard'
    | '/profile'
    | '/admin/dashboard'
    | '/admin'
    | '/admin/communities'
    | '/admin/communities/$organizationId/members'
    | '/admin/communities/$organizationId/settings'
    | '/admin/communities/$organizationId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/onboard'
    | '/profile'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/communities/$organizationId'
    | '/admin/communities/'
    | '/admin/communities/$organizationId/members'
    | '/admin/communities/$organizationId/settings'
    | '/admin/communities/$organizationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communities/': {
      id: '/admin/communities/'
      path: '/communities'
      fullPath: '/admin/communities/'
      preLoaderRoute: typeof AdminCommunitiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communities/$organizationId': {
      id: '/admin/communities/$organizationId'
      path: '/communities/$organizationId'
      fullPath: '/admin/communities/$organizationId'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdRouteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communities/$organizationId/': {
      id: '/admin/communities/$organizationId/'
      path: '/'
      fullPath: '/admin/communities/$organizationId/'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdIndexRouteImport
      parentRoute: typeof AdminCommunitiesOrganizationIdRouteRoute
    }
    '/admin/communities/$organizationId/settings': {
      id: '/admin/communities/$organizationId/settings'
      path: '/settings'
      fullPath: '/admin/communities/$organizationId/settings'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdSettingsRouteImport
      parentRoute: typeof AdminCommunitiesOrganizationIdRouteRoute
    }
    '/admin/communities/$organizationId/members': {
      id: '/admin/communities/$organizationId/members'
      path: '/members'
      fullPath: '/admin/communities/$organizationId/members'
      preLoaderRoute: typeof AdminCommunitiesOrganizationIdMembersRouteImport
      parentRoute: typeof AdminCommunitiesOrganizationIdRouteRoute
    }
  }
}

interface AdminCommunitiesOrganizationIdRouteRouteChildren {
  AdminCommunitiesOrganizationIdMembersRoute: typeof AdminCommunitiesOrganizationIdMembersRoute
  AdminCommunitiesOrganizationIdSettingsRoute: typeof AdminCommunitiesOrganizationIdSettingsRoute
  AdminCommunitiesOrganizationIdIndexRoute: typeof AdminCommunitiesOrganizationIdIndexRoute
}

const AdminCommunitiesOrganizationIdRouteRouteChildren: AdminCommunitiesOrganizationIdRouteRouteChildren =
  {
    AdminCommunitiesOrganizationIdMembersRoute:
      AdminCommunitiesOrganizationIdMembersRoute,
    AdminCommunitiesOrganizationIdSettingsRoute:
      AdminCommunitiesOrganizationIdSettingsRoute,
    AdminCommunitiesOrganizationIdIndexRoute:
      AdminCommunitiesOrganizationIdIndexRoute,
  }

const AdminCommunitiesOrganizationIdRouteRouteWithChildren =
  AdminCommunitiesOrganizationIdRouteRoute._addFileChildren(
    AdminCommunitiesOrganizationIdRouteRouteChildren,
  )

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCommunitiesOrganizationIdRouteRoute: typeof AdminCommunitiesOrganizationIdRouteRouteWithChildren
  AdminCommunitiesIndexRoute: typeof AdminCommunitiesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCommunitiesOrganizationIdRouteRoute:
    AdminCommunitiesOrganizationIdRouteRouteWithChildren,
  AdminCommunitiesIndexRoute: AdminCommunitiesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
